package app.knotwork.android.domain.models

/**
 * Persistent record of one human-in-the-loop interaction a parked run is
 * waiting on.
 *
 * Created when a run stops to ask the user something and cannot hold the
 * question in memory until it is answered: the engine coroutine ends, the
 * foreground service is released, and this record — together with the run
 * record's `WAITING_*` status — is what survives process death and lets the
 * user answer hours later from a notification or by reopening the chat.
 *
 * The two HITL gates (tool approval, clarification question) reach that point
 * by *timing out* of a live in-process waiting phase. The ceiling gate has no
 * live phase: nothing is in flight when a ceiling binds — the walk is between
 * nodes — so there is nothing a live wait would preserve that the checkpoint
 * does not, and the record is written straight away.
 *
 * The record is strictly one-shot: the user's response ([decision] or
 * [answer]) is written onto it before the run is resumed, and the resumed
 * node executor consumes the record (deletes it) exactly once. Binding the
 * response to the recorded request snapshot ([toolName] + [toolArgs]) is the
 * TOCTOU guard — if the re-executed node resolves different arguments, the
 * stale response must not authorise them and a fresh approval is raised.
 *
 * @property runId Id of the parked pipeline run; primary key — a run waits on
 *   at most one interaction at a time.
 * @property sessionId Id of the owning chat session, for session-scoped UI
 *   lookup on reattach.
 * @property kind Which HITL gate the run is parked on. See [PendingInteractionKind].
 * @property toolName Name of the tool awaiting approval; `null` for
 *   clarification records.
 * @property toolArgs JSON argument string of the tool call awaiting approval,
 *   exactly as resolved when the gate was raised; `null` for clarification
 *   records.
 * @property risk Risk classification of the tool awaiting approval; `null`
 *   for clarification records.
 * @property question The clarifying question generated by the LLM; persisted
 *   so resume can re-render it without re-running inference. `null` for
 *   approval records.
 * @property options Optional answer choices of the clarifying question;
 *   `null` for approval records or free-form questions.
 * @property decision The user's approval decision recorded after the park;
 *   `null` while the interaction is still unanswered. See [PendingDecision].
 * @property answer The user's clarification answer recorded after the park;
 *   `null` while unanswered.
 * @property ceilingAxis Which ceiling the run spent; `null` for approval and
 *   clarification records. Persisted rather than re-derived because the answer
 *   buys one more portion **of that axis**, and by the time it arrives the
 *   ledger has been rebuilt in another process — possibly against settings the
 *   user has since edited.
 * @property ceilingLimit The limit that bound, in the axis's own unit; `null`
 *   for the other two kinds. Persisted for the same reason [ceilingAxis] is,
 *   and because the card the user answers has to state the number *that run*
 *   was stopped at, not the number the setting holds today.
 * @property ceilingSpent What the run tree had charged when the limit bound;
 *   `null` for the other two kinds.
 * @property requestedAt Epoch millis when the persistent waiting phase began.
 *   The background approval window (`backgroundApprovalWindowHours` setting)
 *   counts from this moment.
 * @property requestId Identity of the approval request this record parks — the
 *   token the gate minted when it raised the request, carried by the card and
 *   both notifications. An answer is recorded here only when it names this
 *   token, so an answer given for one request can never land on the record that
 *   replaced it (a re-park of the same run REPLACEs the row). `null` for
 *   clarification and ceiling records; records parked before tokens existed
 *   carry their [runId], which is what their notifications address.
 */
data class PendingInteraction(
    val runId: String,
    val sessionId: String,
    val kind: PendingInteractionKind,
    val toolName: String? = null,
    val toolArgs: String? = null,
    val risk: ToolRisk? = null,
    val question: String? = null,
    val options: List<String>? = null,
    val decision: PendingDecision? = null,
    val answer: String? = null,
    val ceilingAxis: RunCeilingAxis? = null,
    val ceilingLimit: Int? = null,
    val ceilingSpent: Int? = null,
    val requestedAt: Long,
    val requestId: String? = null,
)

/**
 * Reads a parked record back as the ceiling breach it was raised for, or `null`
 * when it is not a complete ceiling record.
 *
 * Every consumer of a ceiling pause — the card that asks it, the notification
 * that carries it, the stop that settles it — needs the axis **and** both
 * numbers, so the "all three or nothing" rule is stated once, here. A partial
 * record is deliberately not repaired with defaults: a zero substituted for a
 * missing spend would read as a run that had used nothing, which is the one
 * thing that cannot be true of a run that just breached.
 *
 * @return The breach, or `null` when this is not a ceiling park or is missing
 *   any of its three fields.
 */
fun PendingInteraction.ceilingBreach(): HardCeilingBreach? {
    if (kind != PendingInteractionKind.CEILING) return null
    val axis = ceilingAxis ?: return null
    val limit = ceilingLimit ?: return null
    val spent = ceilingSpent ?: return null
    return HardCeilingBreach(axis = axis, limit = limit, spent = spent)
}

/**
 * The HITL gate a [PendingInteraction] is parked on.
 */
enum class PendingInteractionKind {
    /** The run waits for the user to approve or deny a staged tool call. */
    APPROVAL,

    /** The run waits for the user to answer a clarifying question. */
    CLARIFICATION,

    /**
     * The run has spent a ceiling and waits for the user to say whether it may
     * carry on. Unlike the other two this gate is not about a step the pipeline
     * wants to take — the run is out of budget, and the answer buys it one more
     * portion of the same allowance rather than removing the limit.
     */
    CEILING,
}

/**
 * The user's recorded response to a parked approval request.
 *
 * Recorded onto the [PendingInteraction] before the run is resumed; the
 * resumed tool node consumes it one-shot, subject to the TOCTOU argument
 * match (see [PendingInteraction]).
 */
enum class PendingDecision {
    /** The user approved the staged tool call. */
    APPROVED,

    /** The user denied the staged tool call. */
    DENIED,
}
