package app.knotwork.android.domain.engine

import app.knotwork.android.domain.models.NodeExecutionResult
import app.knotwork.android.domain.models.NodeType
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * [ModelAuthorship]: which text a run carries forward was written by a model.
 * The answer decides whether the chat's assistant message may be mined into
 * long-term memory, so the pass-through and tool cases matter most.
 */
class ModelAuthorshipTest {

    private fun after(
        type: NodeType,
        output: String?,
        input: String = "in",
        inputByModel: Boolean,
        tool: String? = null,
    ) = ModelAuthorship.after(
        type = type,
        result = output?.let { NodeExecutionResult(outputText = it, resolvedToolName = tool) },
        input = input,
        inputByModel = inputByModel,
    )

    @Test
    fun `given a model node with new text then the text is the model's`() {
        listOf(
            NodeType.LITE_RT,
            NodeType.CLOUD,
            NodeType.SUMMARY,
            NodeType.DECOMPOSITION,
            NodeType.EVALUATION,
            NodeType.OUTPUT,
            NodeType.SKILL,
        ).forEach { type ->
            assertTrue(type.name, after(type, output = "new", inputByModel = false))
        }
    }

    @Test
    fun `given a tool's result then it is not the model's whichever node dispatched it`() {
        assertFalse(after(NodeType.TOOL, output = "page", inputByModel = true, tool = "web.fetch"))
        assertFalse(after(NodeType.SKILL, output = "page", inputByModel = true, tool = "web.fetch"))
    }

    @Test
    fun `given a pass-through node then authorship is carried unchanged`() {
        listOf(NodeType.INPUT, NodeType.IF_CONDITION, NodeType.QUEUE_PROCESSOR, NodeType.OUTPUT).forEach { type ->
            assertTrue(type.name, after(type, output = "in", input = "in", inputByModel = true))
            assertFalse(type.name, after(type, output = "in", input = "in", inputByModel = false))
        }
    }

    @Test
    fun `given an intent router then its routing label does not replace the carried authorship`() {
        assertFalse(after(NodeType.INTENT_ROUTER, output = "search", inputByModel = false))
        assertTrue(after(NodeType.INTENT_ROUTER, output = "search", inputByModel = true))
    }

    @Test
    fun `given no output then authorship is carried unchanged`() {
        assertTrue(after(NodeType.LITE_RT, output = null, inputByModel = true))
        assertFalse(after(NodeType.LITE_RT, output = null, inputByModel = false))
    }

    @Test
    fun `given a node whose text is not generated by a model then it is not the model's`() {
        // A clarification pairs the question with the user's answer; a pipeline's
        // output is whatever its sub-pipeline ended on — unknown counts as not.
        listOf(NodeType.CLARIFICATION, NodeType.PIPELINE, NodeType.TOOL).forEach { type ->
            assertEquals(type.name, false, after(type, output = "new", inputByModel = true))
        }
    }
}
