package app.knotwork.android.data.repositories

import android.content.Context
import app.knotwork.android.domain.models.BundledDocument
import app.knotwork.android.domain.models.DocumentationTarget
import app.knotwork.android.domain.repositories.BundledDocumentationRepository
import androidx.annotation.VisibleForTesting
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import timber.log.Timber
import java.io.IOException
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Reads the documentation the build copied into `assets/docs`.
 *
 * Both the copies and the index are generated by `syncBundledDocs` and checked
 * by `verifyBundledDocs`, so a failure here is never bad data — it is a damaged
 * installation. That is why every failure is a `Result.failure` carrying the
 * cause rather than a silent empty list: the Help screen has a designed state
 * for "this copy did not open", and it tells the user that reinstalling
 * replaces the file.
 *
 * @property context Application context used to open the asset stream.
 */
@Singleton
class AssetBundledDocumentationRepository @Inject constructor(
    @ApplicationContext private val context: Context,
) : BundledDocumentationRepository {

    /** Dispatcher every asset read runs on. Swapped in unit tests. */
    @VisibleForTesting
    internal var dispatcher: CoroutineDispatcher = Dispatchers.IO

    override suspend fun documents(): Result<List<BundledDocument>> = withContext(dispatcher) {
        try {
            Result.success(parseIndex(readAsset(INDEX_ASSET_PATH)))
        } catch (e: IOException) {
            Timber.e(e, "Bundled documentation index could not be read")
            Result.failure(e)
        } catch (e: IllegalArgumentException) {
            // kotlinx.serialization's SerializationException is an
            // IllegalArgumentException, and so are the shape requirements
            // below.
            Timber.e(e, "Bundled documentation index is malformed")
            Result.failure(e)
        } catch (e: NoSuchElementException) {
            // `getValue` on an absent member. Same meaning as the above — the
            // index shipped with this build is not the index it expects — but a
            // different exception type, and missing it would crash the screen
            // that exists to explain the failure.
            Timber.e(e, "Bundled documentation index is missing a required member")
            Result.failure(e)
        }
    }

    override suspend fun content(id: String): Result<String> = withContext(dispatcher) {
        val document = documents().getOrElse { return@withContext Result.failure(it) }
            .firstOrNull { it.id == id }
            ?: return@withContext Result.failure(
                IllegalArgumentException("No bundled document is registered under id '$id'"),
            )
        try {
            Result.success(readAsset(document.assetPath))
        } catch (e: IOException) {
            Timber.e(e, "Bundled document '%s' could not be read", id)
            Result.failure(e)
        }
    }

    /**
     * Reads one asset as text.
     *
     * @param path Path under `assets`.
     * @return The file's full text.
     * @throws IOException when the asset is missing or unreadable.
     */
    private fun readAsset(path: String): String =
        context.assets.open(path).bufferedReader().use { it.readText() }

    /**
     * Parses the generated index.
     *
     * @param json The index file's text.
     * @return One entry per bundled document, in the order the build wrote them.
     * @throws IllegalArgumentException when the index is malformed or was
     *   written in a format this build does not read.
     */
    private fun parseIndex(json: String): List<BundledDocument> {
        val root = Json.parseToJsonElement(json).jsonObject
        val version = root.getValue("formatVersion").jsonPrimitive.int
        require(version == INDEX_FORMAT_VERSION) {
            "Bundled documentation index is format $version, this build reads $INDEX_FORMAT_VERSION"
        }
        return root.getValue("documents").jsonArray.map { element ->
            val document = element.jsonObject
            BundledDocument(
                id = document.getValue("id").jsonPrimitive.content,
                path = document.getValue("path").jsonPrimitive.content,
                assetPath = document.getValue("asset").jsonPrimitive.content,
                anchors = document.getValue("anchors").jsonObject
                    .mapValues { (_, offset) -> offset.jsonPrimitive.int },
                links = document.getValue("links").jsonObject
                    .mapValues { (_, target) -> parseTarget(target.jsonObject) },
            )
        }
    }

    /**
     * Parses one resolved link target.
     *
     * @param target The target's JSON object.
     * @return The typed target.
     * @throws IllegalArgumentException for a kind this build does not know.
     */
    private fun parseTarget(target: JsonObject): DocumentationTarget {
        val anchor = target["anchor"]?.jsonPrimitive?.contentOrNull
        return when (val kind = target.getValue("kind").jsonPrimitive.content) {
            "anchor" -> DocumentationTarget.SameDocument(anchor)
            "bundled" -> DocumentationTarget.Bundled(target.getValue("id").jsonPrimitive.content, anchor)
            "repository" -> DocumentationTarget.Repository(target.getValue("path").jsonPrimitive.content, anchor)
            else -> throw IllegalArgumentException("Unknown documentation link kind '$kind'")
        }
    }

    private companion object {
        /** Path of the generated index under `assets`. */
        const val INDEX_ASSET_PATH = "docs/index.json"

        /**
         * Index shape this build reads.
         *
         * Mirrors `BundledDocs.INDEX_FORMAT_VERSION`. The two cannot share a
         * constant — `buildSrc` is invisible from here — so the check exists to
         * turn a silent misreading into a named failure.
         */
        const val INDEX_FORMAT_VERSION = 1
    }
}
