package app.knotwork.design.screens.files

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onRoot
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.knotwork.design.KnotworkRoborazziOptions
import app.knotwork.design.a11y.FixedKnotworkA11y
import app.knotwork.design.a11y.LocalKnotworkA11y
import app.knotwork.design.theme.KnotworkTheme
import com.github.takahirom.roborazzi.captureRoboImage
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode

@RunWith(AndroidJUnit4::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(sdk = [36], qualifiers = "w360dp-h760dp-xhdpi")
class FilesContentSnapshotTest {
    @get:Rule
    val composeTestRule = createComposeRule()

    @Test fun files_empty_light() = snapshot("empty", dark = false) { FilesContent(state = FilesPreview.empty()) }

    @Test fun files_empty_dark() = snapshot("empty", dark = true) { FilesContent(state = FilesPreview.empty()) }

    @Test fun files_populated_light() = snapshot("populated", dark = false) {
        FilesContent(state = FilesPreview.populated())
    }

    @Test fun files_populated_dark() = snapshot("populated", dark = true) {
        FilesContent(state = FilesPreview.populated())
    }

    @Test fun files_selection_light() = snapshot("selection", dark = false) {
        FilesContent(state = FilesPreview.selection())
    }

    @Test fun files_selection_dark() = snapshot("selection", dark = true) {
        FilesContent(state = FilesPreview.selection())
    }

    @Test fun files_preview_light() = snapshot("preview", dark = false) { FilesContent(state = FilesPreview.preview()) }

    @Test fun files_preview_dark() = snapshot("preview", dark = true) { FilesContent(state = FilesPreview.preview()) }

    @Test fun files_preview_large_light() =
        snapshot("preview_large", dark = false) { FilesContent(state = FilesPreview.previewLarge()) }

    @Test fun files_error_light() = snapshot("error", dark = false) { FilesContent(state = FilesPreview.error()) }

    @Test fun files_error_dark() = snapshot("error", dark = true) { FilesContent(state = FilesPreview.error()) }

    @Test fun files_quota_near_light() =
        snapshot("quota_near", dark = false) { FilesContent(state = FilesPreview.quotaNear()) }

    @Test fun files_quota_over_light() =
        snapshot("quota_over", dark = false) { FilesContent(state = FilesPreview.quotaOver()) }

    @Test fun files_delete_light() = snapshot("delete", dark = false) {
        FilesContent(state = FilesPreview.deleteSingle())
    }

    @Test fun files_delete_bulk_light() =
        snapshot("delete_bulk", dark = false) { FilesContent(state = FilesPreview.deleteBulk()) }

    @Test fun files_collision_light() = snapshot("collision", dark = false) {
        FilesContent(state = FilesPreview.collision())
    }

    private fun snapshot(name: String, dark: Boolean, content: @Composable () -> Unit) {
        composeTestRule.setContent {
            KnotworkTheme(darkTheme = dark) {
                CompositionLocalProvider(LocalKnotworkA11y provides FixedKnotworkA11y(reducedMotion = true)) {
                    content()
                }
            }
        }
        val themeTag = if (dark) "dark" else "light"
        composeTestRule.onRoot().captureRoboImage(
            roborazziOptions = KnotworkRoborazziOptions,
            filePath = "src/test/snapshots/files_${name}_$themeTag.png",
        )
    }
}

/** Preview fixtures for the Files screen snapshot matrix. */
internal object FilesPreview {

    private val previewBody = """
        # Q2 competitive scan

        Generated by pipeline "Multi-step research" · 2026-06-13 09:41

        ## Summary
        - 6 vendors evaluated against the on-device LiteRT delegate matrix.
        - Hybrid routing wins on p95 latency for >2B models;
          pure on-device wins on cold-start and privacy.
    """.trimIndent()

    private fun files(): List<FileRowItem> = listOf(
        FileRowItem("exports/contacts.csv", "exports/", "contacts.csv", "1.1 KB", "3 d", FileKind.Text),
        FileRowItem("market-summary.md", "", "market-summary.md", "12.4 KB", "2 h", FileKind.Text, isFresh = true),
        FileRowItem("model-trace.bin", "", "model-trace.bin", "1.4 MB", "1 w", FileKind.Binary),
        FileRowItem("reports/arxiv-notes.txt", "reports/", "arxiv-notes.txt", "3.8 KB", "3 d", FileKind.Text),
        FileRowItem("reports/q2-scan.json", "reports/", "q2-scan.json", "9.2 KB", "1 d", FileKind.Text),
        FileRowItem(
            "reports/q2-competitive-scan.md",
            "reports/",
            "q2-competitive-scan.md",
            "48.1 KB",
            "1 d",
            FileKind.Text,
        ),
        FileRowItem("scratch.txt", "", "scratch.txt", "220 B", "5 d", FileKind.Text),
    )

    private fun normalQuota() =
        QuotaView(count = 7, usageText = "1.5 MB / 64 MB", fraction = 0.02f, tone = QuotaTone.Normal)

    fun empty(): FilesViewState = FilesViewState(
        visualState = FilesVisualState.Empty,
        quota = QuotaView(count = 0, usageText = "0 B / 64 MB", fraction = 0f, tone = QuotaTone.Normal),
    )

    fun populated(): FilesViewState = FilesViewState(
        visualState = FilesVisualState.Populated,
        quota = normalQuota(),
        files = files(),
    )

    fun selection(): FilesViewState = populated().copy(
        selectionMode = true,
        selectedPaths = setOf("market-summary.md", "reports/q2-competitive-scan.md"),
    )

    fun preview(): FilesViewState = populated().copy(
        preview = PreviewView(
            path = "reports/q2-competitive-scan.md",
            dir = "reports/",
            name = "q2-competitive-scan.md",
            sizeLabel = "48.1 KB",
            body = previewBody,
        ),
    )

    fun previewLarge(): FilesViewState = populated().copy(
        preview = PreviewView(
            path = "model-trace-decoded.log",
            dir = "",
            name = "model-trace-decoded.log",
            sizeLabel = "2.3 MB",
            body = previewBody,
            truncated = true,
            shownBytesLabel = "64 KB",
        ),
    )

    fun error(): FilesViewState = FilesViewState(visualState = FilesVisualState.Error)

    fun quotaNear(): FilesViewState = populated().copy(
        quota = QuotaView(count = 7, usageText = "58.6 MB / 64 MB · 92%", fraction = 0.92f, tone = QuotaTone.Warn),
    )

    fun quotaOver(): FilesViewState = populated().copy(
        quota = QuotaView(
            count = 7,
            usageText = "64 MB / 64 MB · full",
            fraction = 1f,
            tone = QuotaTone.Over,
            full = true,
        ),
    )

    fun deleteSingle(): FilesViewState = populated().copy(
        deleteDialog = DeleteDialogView(names = listOf("scratch.txt"), count = 1),
    )

    fun deleteBulk(): FilesViewState = populated().copy(
        deleteDialog = DeleteDialogView(
            names = listOf("market-summary.md", "reports/q2-competitive-scan.md", "exports/contacts.csv"),
            count = 3,
        ),
    )

    fun collision(): FilesViewState = populated().copy(
        collisionDialog = CollisionView(name = "market-summary.md", keepBothName = "market-summary (1).md"),
    )
}
