package app.knotwork.android.toolsprobe

import android.os.Build
import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.appfunctions.AppFunctionData
import androidx.appfunctions.AppFunctionManager
import androidx.appfunctions.AppFunctionSearchSpec
import androidx.appfunctions.ExecuteAppFunctionRequest
import androidx.appfunctions.ExecuteAppFunctionResponse
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Debug-only launcher activity for the `:tools-probe` module.
 *
 * Exposes a single button that builds an [ExecuteAppFunctionRequest] targeting the
 * agent's `AgentAppFunctionService#search` AppFunction (package `app.knotwork.android`, identifier
 * generated by the AppFunctions KSP compiler as `<ClassFQN>#<methodName>`) with the query
 * "Knotwork" and dispatches it through [AppFunctionManager]. The result is rendered below
 * the button so a human running the probe on a Samsung Galaxy S25 Ultra (the
 * reference device) can confirm with a single tap that the agent's callee-side surface is
 * reachable from another app.
 *
 * Construction of the parameter [AppFunctionData] is metadata-driven: the only public
 * [AppFunctionData.Builder] constructors require an
 * [androidx.appfunctions.metadata.AppFunctionParameterMetadata] list paired with the
 * function's [androidx.appfunctions.metadata.AppFunctionComponentsMetadata]. The activity
 * fetches both through [AppFunctionManager.searchAppFunctions] for the agent
 * package — the same discovery surface the agent itself uses for foreign AppFunctions.
 *
 * The Compose state is owned by the activity's lifecycle scope; the activity is
 * intentionally not a `ViewModel`-backed screen because the probe has no need for
 * configuration-change persistence, deep-linking or testing in isolation — its job is to
 * be a thin, manually-driven trigger for the same code path that the instrumented test
 * exercises automatically.
 */
class MainActivity : ComponentActivity() {

    private val state = MutableStateFlow<ProbeState>(ProbeState.Idle)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                Surface(modifier = Modifier.fillMaxSize()) {
                    ProbeScreen(
                        state = state.asStateFlow(),
                        onInvokeSearch = { invokeSearch() },
                    )
                }
            }
        }
    }

    private fun invokeSearch() {
        state.value = ProbeState.InFlight
        lifecycleScope.launch {
            val outcome = runCatching { withContext(Dispatchers.IO) { executeSearchTool() } }
            state.value = outcome.fold(
                onSuccess = { ProbeState.Success(it) },
                onFailure = { throwable ->
                    Log.w(LOG_TAG, "search_tool probe failed", throwable)
                    ProbeState.Failure(throwable.message ?: throwable::class.java.simpleName)
                },
            )
        }
    }

    private suspend fun executeSearchTool(): String {
        val manager = AppFunctionManager.getInstance(applicationContext)
            // Null has more than one cause since `minSdk` dropped to 34: below
            // API 34 the manager never exists, on 34-35 it exists only where the
            // platform ships the AppFunctions extension sidecar, and a work
            // profile is refused at any level. Naming one cause would misdiagnose
            // the other two.
            ?: error(
                "AppFunctionManager unavailable on API ${Build.VERSION.SDK_INT}: " +
                    "needs API 36+, or API 34-35 with the AppFunctions extension present, " +
                    "and never resolves inside a work profile.",
            )
        val metadata = manager
            .searchAppFunctions(AppFunctionSearchSpec(packageNames = setOf(AGENT_PACKAGE)))
            .firstOrNull { it.id == SEARCH_TOOL_ID }
            ?: run {
                // Long-form diagnostic goes to logcat so the UI can stay short. On stock
                // Android 16 this branch is the expected outcome — EXECUTE_APP_FUNCTIONS is
                // declared `internal|privileged`, so a developer-installed probe cannot observe
                // another package's AppFunctions even if they are correctly published (PR #126).
                Log.w(
                    LOG_TAG,
                    "searchAppFunctions returned no entries for package=$AGENT_PACKAGE. " +
                        "Expected on stock Android 16: EXECUTE_APP_FUNCTIONS is declared " +
                        "`internal|privileged`, so cross-package discovery is blocked. " +
                        "Verify the agent APK still ships the inventory with: " +
                        "`unzip -p <agent-apk> assets/knotwork_app_functions.xml`. If the " +
                        "entry is missing, confirm AgentAppFunctionService.search is annotated " +
                        "with @AppFunction so KSP regenerates it.",
                )
                error("Agent AppFunctions are not visible to this probe on this device.")
            }
        val parameters = AppFunctionData.Builder(metadata.parameters, metadata.components)
            .setString("query", "Knotwork")
            .setString("lang", "en")
            .build()
        val request = ExecuteAppFunctionRequest(
            targetPackageName = AGENT_PACKAGE,
            functionIdentifier = SEARCH_TOOL_ID,
            functionParameters = parameters,
        )
        return when (val response = manager.executeAppFunction(request)) {
            is ExecuteAppFunctionResponse.Success ->
                response.returnValue.getString(ExecuteAppFunctionResponse.Success.PROPERTY_RETURN_VALUE).orEmpty()
            is ExecuteAppFunctionResponse.Error -> {
                Log.w(LOG_TAG, "executeAppFunction returned Error: ${response.error}")
                error(response.error.message ?: response.error::class.java.simpleName)
            }
        }
    }

    private companion object {
        const val LOG_TAG = "ToolsProbe"
        const val AGENT_PACKAGE = "app.knotwork.android"

        /**
         * KSP-generated AppFunction wire id for `AgentAppFunctionService.search`. The
         * literal embeds backticks around `data` because the AppFunctions compiler emits
         * Kotlin source-level package escaping into the id string when a package segment
         * collides with a soft keyword — see the agent-side
         * `KnotworkAppFunctionService.FUNCTION_ID_SEARCH` constant. Kept as a literal here
         * because the generated constant lives in the `:app` module and is not visible to
         * this probe.
         */
        const val SEARCH_TOOL_ID =
            "app.knotwork.android.`data`.tools.local.appfunctions.AgentAppFunctionService#search"
    }
}

private sealed interface ProbeState {
    data object Idle : ProbeState
    data object InFlight : ProbeState
    data class Success(val payload: String) : ProbeState
    data class Failure(val message: String) : ProbeState
}

@Composable
private fun ProbeScreen(
    state: StateFlow<ProbeState>,
    onInvokeSearch: () -> Unit,
) {
    val current by state.collectAsState()
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(PaddingValues(horizontal = 24.dp, vertical = 32.dp)),
        verticalArrangement = Arrangement.Top,
    ) {
        Text(text = stringResource(id = R.string.probe_header), style = MaterialTheme.typography.headlineSmall)
        Spacer(modifier = Modifier.height(16.dp))
        Button(onClick = onInvokeSearch, enabled = current !is ProbeState.InFlight) {
            Text(text = stringResource(id = R.string.probe_invoke_search_button))
        }
        Spacer(modifier = Modifier.height(24.dp))
        when (val snapshot = current) {
            ProbeState.Idle -> Text(text = stringResource(id = R.string.probe_idle_message))
            ProbeState.InFlight -> Text(text = stringResource(id = R.string.probe_in_flight_message))
            is ProbeState.Success -> {
                Text(
                    text = stringResource(id = R.string.probe_result_label),
                    style = MaterialTheme.typography.titleSmall,
                )
                Spacer(modifier = Modifier.height(8.dp))
                Text(text = snapshot.payload)
            }
            is ProbeState.Failure -> {
                Text(
                    text = stringResource(id = R.string.probe_error_label),
                    style = MaterialTheme.typography.titleSmall,
                )
                Spacer(modifier = Modifier.height(8.dp))
                Text(text = snapshot.message, color = MaterialTheme.colorScheme.error)
            }
        }
    }
}
