"""Records the embedding of every fact in supersede_pairs_source.json with the app's bundled
on-device embedder and writes supersede_pairs.json, the fixture the memory tests read.

The vectors are a recording of the shipped model, not synthetic data, so the JVM tests run on the
geometry the app really has. Re-record only when the bundled model changes (the fixture test
compares the model's SHA-256 with the one recorded here).

    python3 -m venv /tmp/mp && /tmp/mp/bin/pip install mediapipe==1.0.1
    /tmp/mp/bin/python app/src/test/resources/memory/record_supersede_vectors.py

Runs MediaPipe's TextEmbedder with default options — no L2 normalisation, no quantisation — as
the app's MediaPipeTextEmbeddingEngine does.
"""
import hashlib
import json
import math
import os

import mediapipe
from mediapipe.tasks.python import BaseOptions, text

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", ".."))
MODEL = os.path.join(ROOT, "app", "src", "main", "assets", "universal_sentence_encoder.tflite")
SOURCE = os.path.join(HERE, "supersede_pairs_source.json")
TARGET = os.path.join(HERE, "supersede_pairs.json")
VERDICT_BY_CLASS = {"paraphrase": "SAME", "correction": "UPDATE", "distinct": "DIFFERENT", "unrelated": "DIFFERENT"}
DECIMALS = 6


def cosine(a, b):
    dot = sum(x * y for x, y in zip(a, b))
    return dot / (math.sqrt(sum(x * x for x in a)) * math.sqrt(sum(y * y for y in b)))


def main():
    with open(MODEL, "rb") as model_file:
        model_sha256 = hashlib.sha256(model_file.read()).hexdigest()
    embedder = text.TextEmbedder.create_from_options(
        text.TextEmbedderOptions(base_options=BaseOptions(model_asset_path=MODEL)),
    )
    with open(SOURCE, encoding="utf-8") as source_file:
        source = json.load(source_file)

    vectors = {}
    for pair in source["pairs"]:
        for fact in (pair["stored"], pair["incoming"]):
            if fact not in vectors:
                raw = embedder.embed(fact).embeddings[0].embedding
                vectors[fact] = [round(float(value), DECIMALS) for value in raw]

    pairs = []
    for pair in source["pairs"]:
        pairs.append({
            "id": pair["id"],
            "class": pair["class"],
            "verdict": VERDICT_BY_CLASS[pair["class"]],
            "stored": pair["stored"],
            "incoming": pair["incoming"],
            "cosine": round(cosine(vectors[pair["stored"]], vectors[pair["incoming"]]), DECIMALS),
        })

    fixture = {
        "about": source["about"] + [
            "Generated by record_supersede_vectors.py from supersede_pairs_source.json; do not edit by hand.",
        ],
        "embedder": {
            "model": "app/src/main/assets/universal_sentence_encoder.tflite",
            "modelSha256": model_sha256,
            "runtime": "MediaPipe Python " + mediapipe.__version__ + " TextEmbedder, default options",
            "dimension": len(next(iter(vectors.values()))),
        },
        "pairs": pairs,
        "vectors": vectors,
    }
    # One pair per line and one vector per line, so a re-recording diffs fact by fact.
    lines = ["{"]
    for key in ("about", "embedder"):
        lines.append(" %s: %s," % (json.dumps(key), json.dumps(fixture[key], ensure_ascii=False)))
    lines.append(' "pairs": [')
    lines.append(",\n".join("  " + json.dumps(pair, ensure_ascii=False) for pair in pairs))
    lines.append(" ],")
    lines.append(' "vectors": {')
    lines.append(",\n".join(
        "  %s: %s" % (json.dumps(fact, ensure_ascii=False), json.dumps(vector)) for fact, vector in vectors.items()
    ))
    lines.append(" }")
    lines.append("}")
    with open(TARGET, "w", encoding="utf-8") as target_file:
        target_file.write("\n".join(lines) + "\n")
    print("wrote %d pairs, %d vectors, dimension %d" % (len(pairs), len(vectors), fixture["embedder"]["dimension"]))


if __name__ == "__main__":
    main()
