package app.knotwork.android.data.tools.local.appfunctions

import androidx.appfunctions.AppFunctionContext
import androidx.appfunctions.service.AppFunction
import app.knotwork.android.data.tools.local.SearchTool
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Callee-side wrapper around the built-in `search_tool` tool.
 *
 * The [invoke] method is annotated with [AppFunction]; the KSP compiler from
 * `androidx.appfunctions:appfunctions-compiler` consumes the annotation to:
 *
 *  - emit the `app_functions.xml` (and v2) inventory under the APK's `assets/` so the
 *    platform discovery service can advertise the function to other apps;
 *  - generate dispatch infrastructure (`$SearchAppFunction_AppFunctionInvoker` and the
 *    aggregated `AppFunctionInventory`) consumed by the auto-merged
 *    [androidx.appfunctions.service.PlatformAppFunctionService] from `appfunctions-service`.
 *    That platform service is the single callee-side entry point for the agent; we no
 *    longer ship a hand-rolled `AppFunctionService` subclass.
 *
 * The platform-generated function identifier is the canonical
 * `<ClassFQN>#<methodName>` shape — see `SearchAppFunctionIds.INVOKE_ID` (also generated by
 * KSP) for the wire string external callers must supply. **Caveat:** the AppFunctions
 * compiler currently bakes Kotlin source-level package escaping into the id literal when a
 * segment collides with a soft keyword. The `data` segment in this class's package therefore
 * shows up wrapped in backticks (`` `data` ``) inside the wire id, and external callers must
 * include the backticks verbatim. The instrumented end-to-end test and the
 * `:tools-probe` smoke activity both mirror this literal.
 *
 * **Risk classification:** read-only (no user data is touched, no side effects on device
 * state). External callers therefore do not need a Human-in-the-Loop confirmation —
 * matching the in-agent risk for `search_tool` set in `ToolRepositoryImpl`.
 *
 * **What does still apply to an external caller.** This wrapper reaches [SearchTool]
 * directly and never passes through `ToolRepositoryImpl`, so the checks that repository
 * performs — the Tools screen's per-tool switch among them — do not run on this path.
 * What does run is the check [SearchTool] makes itself: while *Block network from local
 * model* is on, the search is refused for every caller. Anything a future caller must not
 * be able to bypass belongs in [SearchTool], not in the repository.
 *
 * **Hilt integration:** the AppFunctions framework calls a no-arg constructor by default,
 * but this wrapper depends on a Hilt-managed [SearchTool]. The agent's [app.knotwork.android.App]
 * therefore implements [androidx.appfunctions.service.AppFunctionConfiguration.Provider]
 * and registers a factory that resolves [SearchAppFunction] from the singleton component,
 * so the callee-side instance shares caches and rate limits with the in-agent caller path.
 */
@Singleton
class SearchAppFunction @Inject constructor(private val searchTool: SearchTool) {

    /**
     * Executes a Wikipedia search on behalf of an external caller.
     *
     * @param context Per-invocation context supplied by the AppFunctions runtime. Required
     *   by the framework to be the first parameter of every `@AppFunction`; intentionally
     *   unused here because the wrapper has no per-caller policy decisions to make.
     * @param query Non-blank search term. Blank input raises [IllegalArgumentException],
     *   which the AppFunctions framework translates into a typed
     *   `ERROR_INVALID_ARGUMENT` outcome for the platform AppFunctions API.
     * @param lang Wikipedia language code matching the language of [query] (`en`,
     *   `de`, `simple`, …). The AppFunctions KSP compiler does not honour Kotlin
     *   defaults, so the parameter is required at the wire level; an empty or blank
     *   value falls back to `"en"` here so external callers can still omit a meaningful
     *   language hint. Any other value that cannot name a Wikipedia edition raises
     *   [IllegalArgumentException], like a blank [query] — [SearchTool] would refuse it
     *   anyway, and a typed error tells the caller so instead of a result string.
     * @return The article extract (truncated or LLM-summarized) returned by
     *   [SearchTool.executeSearch].
     */
    @AppFunction
    @Suppress("UnusedParameter")
    suspend fun invoke(context: AppFunctionContext, query: String, lang: String): String {
        require(query.isNotBlank()) { "search_tool requires a non-blank 'query' argument" }
        val effectiveLang = lang.ifBlank { DEFAULT_LANG }
        require(SearchTool.wikipediaEdition(effectiveLang) != null) {
            "search_tool requires 'lang' to be a Wikipedia language code such as \"en\""
        }
        return searchTool.executeSearch(query, effectiveLang)
    }

    private companion object {
        const val DEFAULT_LANG = "en"
    }
}
